name: Format and Lint Terraform
on:
  push:
  pull_request:
    branches: [main]

jobs:
  tf_fmt_lint:
    name: Format and Lint Terraform
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_DEFAULT_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Cache Plugin Dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2

      - name: Format Terraform Files
        id: fmt
        run: terraform fmt -recursive
        continue-on-error: true

      - name: Detect Modified Files and Commit
        if: ${{ !github.event.act }} # skip during local actions testing
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: "**/*.tf"
          commit_message: "chore: automatic terraform formatting"
          branch: main

      - name: Run TFlint in Docker Container
        run: |
          docker run --rm -v $(pwd)/terraform/src:/data -t ghcr.io/terraform-linters/tflint
