name: Fix terraform file formatting
on:
  push:
    branches:
      - main
jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_DEFAULT_REGION: eu-west-1
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -recursive
      continue-on-error: true

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        add_options: '**/*.tf'
        commit_message: "chore: automatic terraform formatting"
        push_options: origin main
