name: Fix terraform file formatting
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tf_fmt:
    name: Format and Lint Terraform
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_DEFAULT_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2

      - name: Format Terraform Files
        id: fmt
        run: terraform fmt -recursive
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: "**/*.tf"
          commit_message: "chore: automatic terraform formatting"
          branch: main

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_version: v0.38.1

      - name: Show TFlint Version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init terraform/src/

      - name: Run TFLint
        run: tflint terraform/src/ --format compact
