---
name: Deploy Terraform
on:
    push:
    pull_request:
        branches: [main]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    AWS_DEFAULT_REGION: eu-west-1
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    pre-commit:
        name: Run pre-commit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - name: Install Poetry
              uses: snok/install-poetry@v1
            - name: Install pre-commit
              run: |
                  python -m pip install --upgrade pip setuptools wheel
                  poetry export -f requirements.txt --output requirements.txt
                  pip install -r requirements.txt
            - name: Run pre-commit
              run: |
                  SKIP=terraform_tflint pre-commit run --all-files

    tf_fmt_lint:
        name: Format and Lint Terraform
        runs-on: ubuntu-latest
        needs: [pre-commit]
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Set Cache Plugin Dir
              uses: actions/cache@v3
              with:
                  path: ~/.tflint.d/plugins
                  key: tflint-${{ hashFiles('.tflint.hcl') }}

            - name: Terraform Setup
              uses: hashicorp/setup-terraform@v2

            - name: Format Terraform Files
              id: fmt
              run: terraform fmt -recursive
              continue-on-error: true

            - name: Run TFlint in Docker Container
              run: |
                  docker run --rm -v $(pwd)/terraform/src:/data -t ghcr.io/terraform-linters/tflint

    terraform_apply:
        name: Run Terraform Apply
        runs-on: ubuntu-latest
        needs: [tf_fmt_lint]
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Initialize Terraform
              run: |
                  cd terraform/src && terraform init

            - name: Terraform Plan
              run: |
                  cd terraform/src &&
                  terraform plan \
                  -var 'db_username=${{ secrets.DB_USERNAME }}' \
                  -var 'db_password=${{ secrets.DB_PASSWORD }}' \
                  -var 'my_ip_addresses=${{ secrets.IP_ADDRESSES }}' \
                  -out=terraform.plan

            - name: Terraform Apply
              run: |
                  cd terraform/src &&
                  terraform apply terraform.plan
